### ISSUE TITLE
How to achieve from opaque to transparent between the card?

### ISSUE THREAD

**Issue by wwdc14yh** [filletofish/CardsLayout#10]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/11381801/46931304-30062a80-d07d-11e8-8b3d-ab19dfce7ee4.png">

How to achieve from opaque to transparent between the card?

Thank you

**Comment by filletofish** [comment]
Hi @wwdc14,

I think the way you could achieve that is altering the behaviour of function `computeLayoutAttributesForItem..` at `CardsCollectionViewLayout.swift l:114` by using `percentageDeltaOffset` to set alpha you need.
