### ISSUE TITLE
Support for visibility of previous cell

### ISSUE THREAD

**Issue by satishVekariya** [filletofish/CardsLayout#11]
Need support to display previous item edge at left side of collectionview
![screenshot 2018-10-15 at 4 06 51 pm](https://user-images.githubusercontent.com/17096532/46946113-5a171700-d094-11e8-8bd5-9b49b3b12b5f.png)

**Comment by satishVekariya** [comment]
https://github.com/satishVekariya/PushpaCollectionViewLayout

**Comment by filletofish** [comment]
Hi,

I think the way you could achieve that is altering the behaviour of function `computeLayoutAttributesForItem` at `CardsCollectionViewLayout.swift l:114` by using `percentageDeltaOffset` to set `center.x` you need.


Actually, you can create an hook (delegate or callback) for custom changes for the cell that would be called in `computeLayoutAttributesForItem` and form it in separate Pull Request. So anyone can alter the behaviour without changing the source code.
