### ISSUE TITLE
How to change the offset of the cell behind the first item?

### ISSUE THREAD

**Issue by dannylnz** [filletofish/CardsLayout#12]
[Basically like this](https://imgur.com/XT7aUMx)
I am trying to shift the cells behind the first one in order to better see the other content.

**Comment by filletofish** [comment]
Hi,
Try to use `spacing` parameter to achieve this effect.

**Comment by dannylnz** [comment]
Thanks.
I actually tried on an iPhone X and it's working.
Not sure why is not showing up inside the simulator...
