### ISSUE TITLE
Disable swipe to previous card

### ISSUE THREAD

**Issue by andynadheer** [filletofish/CardsLayout#14]
Is there a way to only swipe to next card? The user should not be able to scroll back to previous card. Also, is there a way to swipe away the last card?

**Comment by filletofish** [comment]
Hi @andynadheer. Thank you for considering the library. 

You can take a look at these [options](https://stackoverflow.com/questions/33141773/disabling-the-scrollview-right-side-at-some-conditions#comment54097085_33142899) or just google 'locking left right directions scrollview' once UICollectionView is inherited from UIScrollView.
