### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by mfamilariSnapp** [filletofish/CardsLayout#16]
Hello and thanks for this great Collection Layout ! 👍

I have a question, is it being considered to handle infinite scroll ?
By infinite scroll I mean, when you scroll a card to the left, it appears at the end of the list.

Thanks in advance

**Comment by filletofish** [comment]
Hi @mfamilariSnapp,

Thank you for your feedback!

Currently it is not considered to handle infinite scroll. However, as it's just a Collection Layout, you can use CollectionView that adopts infinite scroll.

There is a popular project you might take a look. 
https://github.com/nicklockwood/iCarousel

Also, I have open-sourced my rather simple solution of infinite scroll.
https://github.com/filletofish/InfiniteCarousel

**Comment by mfamilariSnapp** [comment]
Thank you for your prompt reply.

I'm going to look at these projects. 👍
