### ISSUE TITLE
Cards Size issue

### ISSUE THREAD

**Issue by Hamza123Imran** [filletofish/CardsLayout#17]
Hi, i have implemented your library in my collection view and when i run the app it shows cards size very small. How can library get the size my collection view cell size? This is my code,
`//Collection View Reload
        self.knowledgeCollectionView.collectionViewLayout = CardsCollectionViewLayout()
        self.knowledgeCollectionView.isPagingEnabled = true
        self.knowledgeCollectionView.showsHorizontalScrollIndicator = false`

**Comment by filletofish** [comment]
Hi @Hamza123Imran,
There is a variable called `itemSize` which you can set in `CardsCollectionViewLayout` to adjust the size.
