### ISSUE TITLE
Shadow with cards 

### ISSUE THREAD

**Issue by hilajqinnovation** [filletofish/CardsLayout#18]
Hi,  thanks for your repository. I just implemented this in my collectionView. And what I need is to add a shadow to the bottom of the highlighted card. I gave the shadow effect to the collectionViewCell, but it is not showing.
Now it is coming like this ,
<img width="356" alt="Screen Shot 2019-06-26 at 11 37 24 AM" src="https://user-images.githubusercontent.com/34735898/60160678-e9b9bb80-9806-11e9-8e33-bfed76dbc05c.png">

**Comment by filletofish** [comment]
Hi,

I am very excited my repository helped you with your piece of work. 

While I would be eager to update repository to fix the bug if there is one, unfortunately, with information you gave me I can't help you with this issue. 

I would advise you to research more what's the problem with shadow, try checking [UIKit docs](https://developer.apple.com) and [stackoverflow](https://stackoverflow.com). Good luck! :)
