### ISSUE TITLE
Unable to resolve the pod

### ISSUE THREAD

**Issue by anverbogatov** [filletofish/CardsLayout#6]
Hi! I have tried to play with the pod in Xcode project, but it turned out that the pod can not be resolved. 
Here's output of `pod install` command:
> ➜  CardsTest pod install
> Analyzing dependencies
> [!] Unable to find a specification for `CardsLayout`

Same for `pod install --repo-update`

**Comment by filletofish** [comment]
@anverbogatov hi! Thank you very much for pointing out the problem!

 It turned out that I had forgot to push it to CocoaPods. Right now it's done. Thanks 👍

**Comment by anverbogatov** [comment]
Thank you for quick response and... welcome to Cocoapods 🤟😁
