### ISSUE TITLE
Move card programatically

### ISSUE THREAD

**Issue by bubudrc** [filletofish/CardsLayout#8]
Hi, before all, awesome work.

I will like to block the user to swipe the card manually and do it programmatically, when I considere necessary, like a stepper. is this possible?

**Comment by filletofish** [comment]
Hi! Thanks! 

Yes, this is possible. One can use extension I have described in #4:

```swift
extension UICollectionView {
  func scrollToItemInCardsLayout(item: Int, animated: Bool) {
    let contentOffset = CGPoint(x: self.bounds.width * CGFloat(item), y: 0)
    self.setContentOffset(contentOffset, animated: animated)
  }
} 
```

To block user to swipe the cards just set `collectionView.isUserInteractionEnabled `

Maybe you will also interested in implementing CollectionView with [infinite scrolling](https://medium.com/@satindersingh71/infinite-uicollectionview-b706c939ed3c) for stepper.

**Comment by bubudrc** [comment]
Great,

Thanks a lot for your help. One thing its that if I set `collectionView.isUserInteractionEnabled = false`, I can touch any button inside the cell. There are another way to stop to the user to not move the `card` manually?

Thanks

**Comment by filletofish** [comment]
@bubudrc try disable the buttons or even the cells manual by changing `isUserInteractionEnabled`.

**Comment by bubudrc** [comment]
hmmm... what I want its to have some buttons on cells (cards) enable, and do the card animation programatically. The user should not be able to swipe the card. it's that possible?

**Comment by filletofish** [comment]
Try to use `isScrollEnabled`
 https://discussions.apple.com/thread/2037566

**Comment by bubudrc** [comment]
that works perfectly... tanks a lot 😄
